// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface CreateTweetParams {
	content: string;
}

export interface FindOneTweetParams {
	id: string;
}

export interface UpdateTweetParams {
	id: string;
	content: string;
}
